spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/planilla_sdb_backup
spring.datasource.username=postgres
spring.datasource.password=1318
spring.datasource.driver-class-name=org.postgresql.Driver

